stages:
    - build
    - package

.production:
    only:
        - /^[0-9]+?\.[0-9]+?\.[0-9]+?$/i

include:
    - local: .gitlab/linux.gitlab-ci.yml
    - local: .gitlab/windows.gitlab-ci.yml
    - local: .gitlab/macos.gitlab-ci.yml

package:
    stage: package
    image: alpine:latest

    extends: .production

    needs:
        - job: linux
          artifacts: true
        - job: linux arm64
          artifacts: true
        - job: macos
          artifacts: true
        - job: windows
          artifacts: true

    script:
        - shopt -s extglob
        - rm -rf !(teaProtocol)
        - mv teaProtocol/* .
        - rm -rf teaProtocol

    artifacts:
        expire_in: 1 day
        paths:
            - linux
            - linux-arm64
            - windows
            - macos
