linux:
    stage: build
    image: $CI_REGISTRY/tivolicloud/interface/build:linux

    extends: .production

    variables:
        BUILD_TYPE: Release
        RELEASE_TYPE: PRODUCTION
        STABLE_BUILD: 1

        RELEASE_NUMBER: $CI_COMMIT_TAG

        TIVOLI_QT_BASE: $CI_PROJECT_DIR/build/TIVOLI_QT
        TIVOLI_VCPKG_BASE: $CI_PROJECT_DIR/build/TIVOLI_VCPKG

    cache:
        paths:
            - build/TIVOLI_QT
            - build/TIVOLI_VCPKG

    script:
        - python3 .gitlab/prepare-interface.py

        - mkdir -p build
        - cd build
        - /usr/local/bin/cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
        - make teaProtocol -j$(nproc)

        - mkdir -p ../teaProtocol-$CI_COMMIT_TAG/linux
        - mv plugins/teaProtocol/libteaProtocol.so ../teaProtocol-$CI_COMMIT_TAG/linux/libteaProtocol-$RELEASE_NUMBER.so

    artifacts:
        expire_in: 1 day
        paths:
            - teaProtocol-$CI_COMMIT_TAG

linux arm64:
    stage: build
    image: $CI_REGISTRY/tivolicloud/interface/build:linux-arm64
    tags:
        - arm64

    extends: .production

    variables:
        BUILD_TYPE: Release
        RELEASE_TYPE: PRODUCTION
        STABLE_BUILD: 1

        RELEASE_NUMBER: $CI_COMMIT_TAG

        TIVOLI_QT_BASE: $CI_PROJECT_DIR/build/TIVOLI_QT
        TIVOLI_VCPKG_BASE: $CI_PROJECT_DIR/build/TIVOLI_VCPKG

    cache:
        paths:
            - build/TIVOLI_QT
            - build/TIVOLI_VCPKG

    script:
        - python3 .gitlab/prepare-interface.py

        - mkdir -p build
        - cd build
        - /usr/local/bin/cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DDISABLE_HIFI_CODEC=ON -DDISABLE_PCM_CODEC=ON
        - make teaProtocol -j$(nproc)

        - mkdir -p ../teaProtocol-$CI_COMMIT_TAG/linux-arm64
        - mv plugins/teaProtocol/libteaProtocol.so ../teaProtocol-$CI_COMMIT_TAG/linux-arm64/libteaProtocol-$RELEASE_NUMBER.so

    artifacts:
        expire_in: 1 day
        paths:
            - teaProtocol-$CI_COMMIT_TAG
