linux:
    stage: build
    image: ubuntu:18.04

    extends: .production

    variables:
        BUILD_TYPE: Release
        RELEASE_TYPE: PRODUCTION
        STABLE_BUILD: 1

        RELEASE_NUMBER: $CI_COMMIT_TAG

        TIVOLI_QT_BASE: $CI_PROJECT_DIR/build/TIVOLI_QT
        TIVOLI_VCPKG_BASE: $CI_PROJECT_DIR/build/TIVOLI_VCPKG

    cache:
        paths:
            - build/TIVOLI_QT
            - build/TIVOLI_VCPKG

    script:
        # ubuntu 18.04
        - apt-get update -y
        - DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential gcc g++ ninja-build git curl zip unzip python3 patchelf wget libssl-dev libdouble-conversion-dev libpng-dev libharfbuzz-dev libgl1-mesa-dev libasound2 libxmu-dev libxi-dev freeglut3-dev libasound2-dev libjack0 libjack-dev libxrandr-dev libudev-dev zlib1g-dev libpcre2-dev libpulse-mainloop-glib0 liblcms2-2 libjpeg-dev libfontconfig1 libxcb-icccm4-dev libxcb-image0-dev libpulse0 libnss3 libnspr4 libxcursor1 libxcomposite1 libxtst6 libxslt1.1 libxss-dev libpci-dev libevent-dev libminizip-dev libxcb-keysyms1-dev libxcb-render-util0-dev libxcb-xinerama0-dev libxcb-xkb-dev libxkbcommon-x11-dev libegl1-mesa-dev libgstreamer-plugins-base1.0-dev libgtk-3-dev libmtdev-dev libinput-dev libxcb-xinput-dev

        - python3 .gitlab/prepare-interface.py

        # cmake 3.14 required for vcpkg
        - curl -O https://cmake.org/files/v3.14/cmake-3.14.2-Linux-x86_64.sh
        - chmod +x cmake-3.14.2-Linux-x86_64.sh
        - ./cmake-3.14.2-Linux-x86_64.sh --prefix=/usr/local --skip-license

        # install nodejs 12
        - curl -sL https://deb.nodesource.com/setup_12.x | bash -
        - apt-get install -y nodejs

        # build
        - mkdir -p build
        - cd build
        - /usr/local/bin/cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
        - make teaProtocol -j$(nproc)

        - mkdir -p ../teaProtocol/linux
        - mv plugins/teaProtocol/libteaProtocol.so ../teaProtocol/linux/libteaProtocol-$RELEASE_NUMBER.so

    artifacts:
        expire_in: 1 day
        paths:
            - teaProtocol

linux arm64:
    stage: build
    image: ubuntu:18.04
    tags:
        - arm64

    extends: .production

    variables:
        BUILD_TYPE: Release
        RELEASE_TYPE: PRODUCTION
        STABLE_BUILD: 1

        RELEASE_NUMBER: $CI_COMMIT_TAG

        TIVOLI_QT_BASE: $CI_PROJECT_DIR/build/TIVOLI_QT
        TIVOLI_VCPKG_BASE: $CI_PROJECT_DIR/build/TIVOLI_VCPKG

    cache:
        paths:
            - build/TIVOLI_QT
            - build/TIVOLI_VCPKG

    script:
        # ubuntu 18.04
        - apt-get update -y
        - DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential gcc g++ ninja-build git curl zip unzip python3 patchelf wget libssl-dev libdouble-conversion-dev libpng-dev libharfbuzz-dev libgl1-mesa-dev libasound2 libxmu-dev libxi-dev freeglut3-dev libasound2-dev libjack0 libjack-dev libxrandr-dev libudev-dev zlib1g-dev libpcre2-dev libpulse-mainloop-glib0 liblcms2-2 libjpeg-dev libfontconfig1 libxcb-icccm4-dev libxcb-image0-dev libpulse0 libnss3 libnspr4 libxcursor1 libxcomposite1 libxtst6 libxslt1.1 libxss-dev libpci-dev libevent-dev libminizip-dev libxcb-keysyms1-dev libxcb-render-util0-dev libxcb-xinerama0-dev libxcb-xkb-dev libxkbcommon-x11-dev libegl1-mesa-dev libgstreamer-plugins-base1.0-dev libgtk-3-dev libmtdev-dev libinput-dev libxcb-xinput-dev

        - python3 .gitlab/prepare-interface.py

        # cmake 3.14 required for vcpkg
        # - curl -O https://cmake.org/files/v3.14/cmake-3.14.2-Linux-x86_64.sh
        # - chmod +x cmake-3.14.2-Linux-x86_64.sh
        # - ./cmake-3.14.2-Linux-x86_64.sh --prefix=/usr/local --skip-license
        # TODO: compiling cmake takes too much time
        - curl -O https://cmake.org/files/v3.14/cmake-3.14.2.tar.gz
        - tar -xf cmake-3.14.2.tar.gz
        - cd cmake-3.14.2
        - ./configure --prefix=/usr/local --parallel=$(nproc)
        - make -j$(nproc)
        - make install -j$(nproc)
        - cd ..

        # install nodejs 12
        - curl -sL https://deb.nodesource.com/setup_12.x | bash -
        - apt-get install -y nodejs

        # build
        - mkdir -p build
        - cd build
        - /usr/local/bin/cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DDISABLE_HIFI_CODEC=ON -DDISABLE_PCM_CODEC=ON
        - make teaProtocol -j$(nproc)

        - mkdir -p ../teaProtocol/linux-arm64
        - mv plugins/teaProtocol/libteaProtocol.so ../teaProtocol/linux-arm64/libteaProtocol-$RELEASE_NUMBER.so

    artifacts:
        expire_in: 1 day
        paths:
            - teaProtocol
