macos:
    stage: build
    tags:
        - macos

    extends: .production

    variables:
        BUILD_TYPE: Release
        RELEASE_TYPE: PRODUCTION
        STABLE_BUILD: 1

        RELEASE_NUMBER: $CI_COMMIT_TAG

        OPENSSL_ROOT_DIR: /usr/local/Cellar/openssl@1.1/1.1.1h
        OPENSSL_INCLUDE_DIR: ${OPENSSL_ROOT_DIR}/include
        OSX_SDK: "10.11"

    script:
        - python .gitlab/prepare-interface.py

        - mkdir -p build
        - cd build

        - cmake
          -DCMAKE_BUILD_TYPE=$BUILD_TYPE
          -DOPENSSL_ROOT_DIR=$OPENSSL_ROOT_DIR
          -DOPENSSL_INCLUDE_DIR=$OPENSSL_INCLUDE_DIR
          -G Ninja ..
        - cmake --build . --config $BUILD_TYPE --target tea-protocol-plugin

        - mkdir -p ../tea-protocol-plugin/macos
        - mv plugins/tea-protocol-plugin/libtivoli-tea-protocol-plugin.dylib
          ../tea-protocol-plugin/macos

    artifacts:
        expire_in: 1 day
        paths:
            - tea-protocol-plugin
