macos:
    stage: build
    tags:
        - macos

    extends: .production

    variables:
        BUILD_TYPE: Release
        RELEASE_TYPE: PRODUCTION
        STABLE_BUILD: 1

        RELEASE_NUMBER: $CI_COMMIT_TAG

        OPENSSL_ROOT_DIR: /usr/local/Cellar/openssl/1.0.2t
        OPENSSL_INCLUDE_DIR: ${OPENSSL_ROOT_DIR}/include
        OPENSSL_USE_STATIC_LIBS: "TRUE"
        OSX_SDK: "10.11"

    script:
        - python .gitlab/prepare-interface.py

        - mkdir -p build
        - cd build

        # TODO: update cmake to use env vars
        - cmake
          -DCMAKE_BUILD_TYPE=$BUILD_TYPE
          -DOPENSSL_ROOT_DIR=$OPENSSL_ROOT_DIR
          -DOPENSSL_INCLUDE_DIR=$OPENSSL_INCLUDE_DIR
          -DOPENSSL_USE_STATIC_LIBS=$OPENSSL_USE_STATIC_LIBS
          -G Xcode ..
        - cmake --build . --target teaProtocol --config $BUILD_TYPE | xcpretty

        - mkdir -p ../teaProtocol-$CI_COMMIT_TAG/macos
        - mv plugins/teaProtocol/Release/libteaProtocol.dylib ../teaProtocol-$CI_COMMIT_TAG/macos/libteaProtocol-$RELEASE_NUMBER.dylib

    artifacts:
        expire_in: 1 day
        paths:
            - teaProtocol
